blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/nooogle/CDS.FluentHtmlReports/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://github.com/nooogle/CDS.FluentHtmlReports/blob/master/README.md
    about: Read the documentation and examples
